---
# Download EPEL for Centos/RHEL version 6
- name: Download EPEL Repo - Centos/RHEL 6
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: Install EPEL Repo - Centos/RHEL 6
  command: rpm -ivh /tmp/epel-release-6-8.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

# Download EPEL for Centos/RHEL version 7
- name: Download EPEL Repo - Centos/RHEL 7
  get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/tmp/epel-release-7.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install EPEL Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/epel-release-7.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install libselinux-python
  yum: name=libselinux-python

# Install policycoreutils-python to get semanage tool
- name: Install policycoreutils-python
  yum: name=policycoreutils-python
  
#- name: Adding Users.
#  user: name=john group=users home=/home/john createhome=yes shell=/bin/bash
