---
- name: add group "apache"
  group: name=apache

- name: add user "apache"
  user: name=apache group=apache home=/var/www createhome=no

- name: install unzip
  yum: name=unzip state=present

- name: Install Apache
  yum: name=httpd state=present

- name: Install Apache Developer Package
  yum: name=httpd state=present

- name: Install mod_ssl
  yum: name=mod_ssl state=present

- name: create certificates directory
  file: path=/etc/httpd/conf/ssl state=directory owner=root group=apache mode=0750

- name: Remove  welcome.conf
  file: name=/etc/httpd/conf.d/welcome.conf state=absent

- name: Remove  autoindex.conf
  file: name=/etc/httpd/conf.d/autoindex.conf state=absent

- name: Install telnet
  yum: name=telnet state=present
